//! Runtime systemd drop-in generation.
//!
//! Session lifetime is anchored to `graphical-session.target`, the standard
//! freedesktop session target. The compositor unit already wires itself to it
//! upstream (niri: `BindsTo=`/`Before=graphical-session.target`), so starting
//! the compositor pulls the target up, and stopping the target tears the
//! compositor — and the session-scoped clients ordered around it — back down
//! in order. session-manager watches that target directly; we do not add a
//! private anchor of our own.
//!
//! What the packaged compositor unit does NOT carry is our crash/quit policy.
//! Since which compositor runs is a config value (`compositor_service`), that
//! policy cannot be shipped statically without pinning the compositor at
//! install time. Instead session-manager drops a per-service override into the
//! user manager's runtime directory at startup, leaving the packaged unit
//! untouched.

use std::path::PathBuf;
use tracing::info;

use crate::scanner::Config;

/// The freedesktop session target session-manager watches. Its ActiveState
/// going inactive is the single definition of "session over".
pub const SESSION_TARGET: &str = "graphical-session.target";

/// Path to the runtime drop-in directory for `service`, under the per-user
/// writable runtime location. This mirrors where `systemctl --user edit
/// --runtime` writes; `/run/systemd/user` is root-owned and unusable here.
fn dropin_dir(runtime_dir: &str, service: &str) -> PathBuf {
    let mut path = PathBuf::from(runtime_dir);
    path.push("systemd/user");
    path.push(format!("{service}.d"));
    path
}

/// Render the drop-in contents defining the compositor's crash/quit policy.
///
/// This carries ONLY policy — no `BindsTo=`/`After=` anchor wiring, because the
/// compositor unit already binds itself to `graphical-session.target` upstream.
/// `Restart=`/`RestartMode=` are single-valued and cleanly override whatever
/// the packaged unit set; `[Unit]` keys are additive over it.
///
/// Policy: the compositor process is never the session authority. The session
/// ends if and only if `graphical-session.target` is stopped. So:
///
/// * `Restart=always` — any compositor exit, clean or crash, respawns it. A
///   clean quit therefore does NOT end the session (no `OnSuccess=` here on
///   purpose), it just gives you a fresh compositor.
/// * `OnFailure=<compositor_shutdown>` — the one exception: when the compositor
///   crash-loops hard enough to exhaust `StartLimitBurst`, the unit enters
///   `failed` and we trigger the shutdown unit (which `Conflicts=` the session
///   target, stopping it) rather than leaving a live session with no
///   compositor. This still honours "only a target stop ends the session" — it
///   is simply another trigger of that stop, alongside the logout keybind.
///
/// `RestartMode=direct` is load-bearing and the reason this requires systemd
/// 254 or newer. Without it, `OnFailure=` fires on *every* crash (verified on
/// systemd 260), so a single absorbed crash would immediately trigger a
/// logout. With `RestartMode=direct` the unit skips the intermediate
/// failed/inactive state on each auto-restart, so `OnFailure=` fires only on
/// the *terminal* transition — the exhausted-start-limit crash-loop.
fn render_dropin(config: &Config) -> String {
    format!(
        "# Generated by session-manager at startup. Do not edit; regenerated\n\
         # each session. Defines {service}'s crash/quit policy; the unit is\n\
         # already bound to graphical-session.target by its packaged definition.\n\
         [Unit]\n\
         OnFailure={shutdown}\n\
         StartLimitIntervalSec={interval}\n\
         StartLimitBurst={burst}\n\
         \n\
         [Service]\n\
         Restart=always\n\
         RestartMode=direct\n",
        service = config.compositor_service,
        shutdown = config.compositor_shutdown,
        interval = config.start_limit_interval_sec,
        burst = config.start_limit_burst,
    )
}

/// Write the runtime drop-in for the configured compositor service.
///
/// `runtime_dir` is `$XDG_RUNTIME_DIR`. The write is idempotent (fixed path and
/// filename), so a re-run cleanly overwrites a stale drop-in. The caller must
/// trigger a daemon reload before starting the unit for systemd to pick it up.
///
/// This is load-bearing: without the drop-in the compositor would restart-loop
/// forever with no crash-loop escape and no start limit, so the caller treats a
/// failure here as fatal rather than best-effort.
pub fn write_compositor_dropin(config: &Config, runtime_dir: &str) -> std::io::Result<()> {
    let dir = dropin_dir(runtime_dir, &config.compositor_service);
    std::fs::create_dir_all(&dir)?;

    let path = dir.join("50-session-manager.conf");
    std::fs::write(&path, render_dropin(config))?;

    info!(
        "wrote compositor drop-in for {} at {}",
        config.compositor_service,
        path.display()
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_config() -> Config {
        Config {
            targets: vec![],
            compositor_service: "niri.service".to_string(),
            compositor_shutdown: "niri-shutdown.target".to_string(),
            start_limit_interval_sec: 30,
            start_limit_burst: 5,
        }
    }

    #[test]
    fn dropin_dir_is_under_runtime_user_systemd() {
        let dir = dropin_dir("/run/user/1000", "niri.service");
        assert_eq!(
            dir,
            PathBuf::from("/run/user/1000/systemd/user/niri.service.d")
        );
    }

    #[test]
    fn dropin_dir_tracks_configured_service_name() {
        // Switching compositors must move the drop-in to that service's dir,
        // so selection stays a pure config concern.
        let dir = dropin_dir("/run/user/1000", "hyprland.service");
        assert!(dir.ends_with("hyprland.service.d"));
    }

    #[test]
    fn render_carries_no_anchor_wiring() {
        // The compositor binds itself to graphical-session.target upstream;
        // the drop-in must NOT add its own anchor edges (that was the old
        // compositor.target design, now removed).
        let out = render_dropin(&test_config());
        assert!(!out.contains("BindsTo="));
        assert!(!out.contains("compositor.target"));
    }

    #[test]
    fn render_routes_only_onfailure_to_shutdown() {
        // Only OnFailure= ends the session (terminal crash-loop), routed to the
        // configured shutdown unit which Conflicts= the session target.
        // OnSuccess= is deliberately absent: a clean compositor exit must
        // respawn, not end the session — only a stop of the target does.
        let out = render_dropin(&test_config());
        assert!(out.contains("OnFailure=niri-shutdown.target"));
        assert!(!out.contains("OnSuccess="));
    }

    #[test]
    fn render_uses_restart_always_not_on_failure() {
        // Restart=always so a clean compositor exit respawns rather than
        // leaving a live session with no compositor. The compositor process is
        // never the session authority.
        let out = render_dropin(&test_config());
        assert!(out.contains("Restart=always"));
        assert!(!out.contains("Restart=on-failure"));
    }

    #[test]
    fn render_uses_restart_mode_direct() {
        // Load-bearing: without RestartMode=direct, OnFailure= fires on every
        // crash (verified on systemd 260), so a single absorbed crash would
        // trigger an immediate logout. direct suppresses the intermediate
        // failed-state transition so OnFailure= only fires on terminal give-up.
        let out = render_dropin(&test_config());
        assert!(out.contains("RestartMode=direct"));
    }

    #[test]
    fn render_interpolates_start_limit_from_config() {
        let config = Config {
            start_limit_interval_sec: 45,
            start_limit_burst: 3,
            ..test_config()
        };
        let out = render_dropin(&config);
        assert!(out.contains("StartLimitIntervalSec=45"));
        assert!(out.contains("StartLimitBurst=3"));
    }

    #[test]
    fn write_then_read_roundtrips_into_service_dropin_dir() {
        let tmp = std::env::temp_dir().join(format!(
            "session-manager-dropin-test-{}",
            std::process::id()
        ));
        let runtime = tmp.to_str().unwrap();

        write_compositor_dropin(&test_config(), runtime).expect("write should succeed");

        let written = std::fs::read_to_string(
            tmp.join("systemd/user/niri.service.d/50-session-manager.conf"),
        )
        .expect("drop-in file should exist");
        assert_eq!(written, render_dropin(&test_config()));

        std::fs::remove_dir_all(&tmp).ok();
    }
}
